language: ruby
sudo: false
dist: trusty
before_install: gem update --system
addons:
  postgresql: "9.6"
matrix:
  include:
  - rvm: ruby-head
    env:
      - LABEL=unit_tests
      - SSHSCAN_API_HOST=127.0.0.1
      - SSHSCAN_API_PORT=8000
      - SSHSCAN_API_ALLOWED_PORTS=22
      - SSHSCAN_API_AUTHENTICATION=false
      - SSHSCAN_DATABASE_HOST=database
      - SSHSCAN_DATABASE_NAME=ssh_observatory
      - SSHSCAN_DATABASE_USERNAME=sshobs
    services:
      - postgres
    script:
      - bundle install
      - chmod u+x database/init-user-db-travis.sh
      - database/init-user-db-travis.sh
      - bundle exec rake spec
    after_success:
      - coveralls
  - rvm: 2.5.0
    env:
      - LABEL=unit_tests
      - SSHSCAN_API_HOST=127.0.0.1
      - SSHSCAN_API_PORT=8000
      - SSHSCAN_API_ALLOWED_PORTS=22
      - SSHSCAN_API_AUTHENTICATION=false
      - SSHSCAN_DATABASE_HOST=database
      - SSHSCAN_DATABASE_NAME=ssh_observatory
      - SSHSCAN_DATABASE_USERNAME=sshobs
    services:
      - postgres
    script:
      - bundle install
      - chmod u+x database/init-user-db-travis.sh
      - database/init-user-db-travis.sh
      - bundle exec rake spec
  - rvm: 2.3.6
    env:
      - LABEL=unit_tests
      - SSHSCAN_API_HOST=127.0.0.1
      - SSHSCAN_API_PORT=8000
      - SSHSCAN_API_ALLOWED_PORTS=22
      - SSHSCAN_API_AUTHENTICATION=false
      - SSHSCAN_DATABASE_HOST=database
      - SSHSCAN_DATABASE_NAME=ssh_observatory
      - SSHSCAN_DATABASE_USERNAME=sshobs
    services:
      - postgres
    script:
      - bundle install
      - chmod u+x database/init-user-db-travis.sh
      - database/init-user-db-travis.sh
      - bundle exec rake spec
  - rvm: 2.2.9
    env:
      - SSHSCAN_API_HOST=127.0.0.1
      - SSHSCAN_API_PORT=8000
      - SSHSCAN_API_ALLOWED_PORTS=22
      - SSHSCAN_API_AUTHENTICATION=false
      - SSHSCAN_DATABASE_HOST=database
      - SSHSCAN_DATABASE_NAME=ssh_observatory
      - SSHSCAN_DATABASE_USERNAME=sshobs
      - LABEL=unit_tests
    services:
      - postgres
    script:
      - bundle install
      - chmod u+x database/init-user-db-travis.sh
      - database/init-user-db-travis.sh
      - bundle exec rake spec
  - rvm: 2.5.0
    env:
      - LABEL=docker_build_and_push
    services:
      - docker
    script:
      - chmod u+x ./build_and_deploy_to_dockerhub.sh
      - ./build_and_deploy_to_dockerhub.sh